#!/bin/bash
#
#  Command Line Interface to start all services associated with the Tutorial
#  For this tutorial the commands are merely a convenience script to run docker or docker compose
#
#  Each services script can be run using either docker compose (the external tool with the hyphen -) 
#  or docker compose (the newer version directly bundled with Docker with a space )
#
#  if you start up with the following command:
#
#  ./services start legacy
#
# This will force the script to use docker compose which may be more reliable in 
# some cases (or if an older version of Docker is being used)

set -e

# export $(grep -v '^#' .env | grep -v '^$' | xargs)
export $(cat .env | grep "#" -v)



ORION="http://orion:1026/version"
# ORION="http://localhost:1026/version"
CONTEXT="https://github.com/Tehedor/smart-LEGO-data-models/blob/main/schemas/datamodels.context-ngsi.jsonld"
CORE_CONTEXT="https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld"
# Models
# https://app.swaggerhub.com/apis-docs/SergioTejedor/Lego_Models/1.0.0


dockerCmd="docker compose"


if (( $# < 1 )); then
	echo "Illegal number of parameters"
	# echo -e "usage: ./services [create|start|stop\n\t\torion|stop-orion\n\t\tdraco|draco-mysql|draco-mongo|draco-postgres|stop-draco\n\t\tsimulator|simulator-marta]"
	displayHelp
	exit 1
fi

pause(){
	printf " "
	count="$1"
	[ "$count" -gt 59 ] && printf "Waiting one minute " || printf " Waiting a few seconds ";
	while [ "$count" -gt 0 ]
	do
		printf "."
		sleep 3
		count=$((count - 3))
	done
	echo ""
}

# Load environment file variables for services
source ./zz_env_services/config_env_files.sh

# wait & stop functions
source ./services_aux_functions.sh

##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### #####
##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### #####
##### ##### ##### ##### Run
##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### #####
##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### ##### #####
displayServices () {
	echo ""
	docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --filter name="$1"
	echo ""
}

command="$1"
argument="$2"
case "${command}" in
	"help")
		displayHelp
		exit 0
		;;
	"build")
        echo "Descargando y construyendo todas las imágenes necesarias..."
        ${dockerCmd} ${envFileOrion} -f orion/orion-ld.yml build
        ${dockerCmd} ${envFileDraco} -f draco/draco-mongo.yml build
        ${dockerCmd} ${envFileProxyReverse} -f proxy-reverse/nginx-reverse.yml build
		docker pull -q node:22.12.0
		docker pull -q node:20.14.0
		docker pull -q redis:8.0.2
		docker pull -q mysql:9.3.0
		docker pull -q minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
		exit 0
        ;;
	"build1")
		echo "Descargando y construyendo las imágenes necesarias para Orion, Draco y Minio..."
		${dockerCmd} ${envFileOrion} -f orion/orion-ld.yml build
		${dockerCmd} ${envFileDraco} -f draco/draco-mongo.yml build
		docker pull -q minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
		exit 0
		;;
	"build2")
		echo "Descargando y construyendo las imágenes necesarias para Simulator y Subs Control App..."
		${dockerCmd} ${envFileSimulator} -f simulator/simulator-app.yml build
		${dockerCmd} ${envFileSubsControl} -f subs-control/subs-control-app.yml pull
		exit 0
		;;
	"build3")
		echo "Descargando y construyendo las imágenes necesarias para Apis App..."
		${dockerCmd} ${envFileApisApp} -f apis_app/apis-app.yml build
		exit 0
		;;
	"orion")
		stoppingContainersOrion
		waitForCoreContext
		echo -e "Starting containers:  \033[1;34mOrion\033[0m, \033[1;36mIoT-Agent\033[0m, \033[1mTutorial\033[0m, a linked data \033[1mContext\033[0m and a \033[1mMongoDB\033[0m database."
		echo -e "- \033[1;34mOrion\033[0m is the context broker"
		echo -e "- Data models \033[1m@context\033[0m (Smart Lego City) is supplied externally"		
		echo ""

		${dockerCmd} ${envFileOrion} -f orion/orion-ld.yml up -d --renew-anon-volumes

		displayServices "orion|context"
		waitForMongoOrion
		waitForOrion
		./services subs-control-app 

		echo -e "\033[1;34m${command}\033[0m is now running and exposed on localhost:${EXPOSED_PORT}"
		;;
	"stop-orion")
		stoppingContainersOrion
		;;
	"draco")
		stoppingContainersDraco
		echo -e "Starting containers:  \033[1mDraco and a \033[1mMySQL\033[0m database."
		echo ""
		${dockerCmd}  ${envFileDraco} -f draco/draco-mongo.yml up -d --renew-anon-volumes
		
		displayServices "draco"
		waitForMongoDraco
		waitForDraco
		waitForDracoInit
		docker rm fiware-draco-init-1 > /dev/null 2>&1 || echo "⚠️ No se pudo eliminar el contenedor"
		;;
	"stop-draco")
		stoppingContainersDraco
		;;
	"nginx")
		echo "Starting Nginx"
		${dockerCmd} ${envFileProxyReverse} -f proxy-reverse/nginx-reverse.yml up -d
		displayServices "nginx-reverse"
		waitForProxyReverse
		;;
	"simulator")
		# python3 scripts/simulatorDocker/iniciarSimulator.py
		stoppingContainerAppSimulator
		echo -e "Starting containers:  \033[1mSimulator app .\033[0m"
		echo ""
		
		${dockerCmd} ${envFileSimulator} -f simulator/simulator-app.yml up -d 
		displayServices "simulator-app"
		waitForSimulatorApp		
		;;
	"stop-simulator")
		stoppingContainerAppSimulator
		;;
	"subs-control-app")
		stoppingContainerAppSubsControl
		echo -e "Starting containers:  \033[1mSubs Control app .\033[0m"
		echo ""
		${dockerCmd} ${envFileSubsControl} -f subs-control/subs-control-app.yml up -d
		displayServices "subs-control-app"
		waitForSubsControlApp
		;;
	"stop-subs-control-app")
		stoppingContainerAppSubsControl
		;;
	"minio-bucket")
		echo "Starting Minio"
		echo ""
		docker compose ${envFileBucketMinio} -f bucket_minio/bucket_minio_photo.yaml up -d
		waitForMinioBucket
		CONTAINER_NAME_MINIO=$(docker compose -f ${ruta}bucket_minio_photo.yaml ps -q minio)
		docker exec -it $CONTAINER_NAME_MINIO /bin/sh /usr/local/bin/init.sh
		displayServices "minio-bucket"
		;;
	"stop-minio-bucket")
		docker compose ${envFileBucketMinio} -f bucket_minio/bucket_minio_photo.yaml down
		stoppingContainerMinioBucket
		;;
	"apis-app")
		echo "Starting Apis App"
		echo ""
		${dockerCmd} ${envFileApisApp} -f apis_app/apis-app.yml up -d
		displayServices "apis-app"
		waitForApisApp
		;;
	"stop-apis-app")
		${dockerCmd} ${envFileApisApp} -f apis_app/apis-app.yml down
		stopContainerApisApp
		;;
	"start1")
		./services  orion 
		./services  draco
		./services  minio-bucket
		;;
	"stop1")
		./services stop-orion
		./services stop-subs-control-app
		./services stop-draco
		./services stop-minio-bucket
		;;
	"start2")
		./services simulator
		;;
	"stop2")
		./services stop-simulator
		;;
	"start3")
		./services apis-app
		;;
	"stop3")
		./services stop-apis-app
		;;
	"stop-all")
		./services stop-orion
		./services stop-subs-control-app
		./services stop-draco
		./services stop-minio-bucket
		./services stop-simulator
		./services stop-apis-app
		;;
	"prune")
		echo "Pruning unused Docker resources"
		docker system prune -f
		docker volume prune -f
		docker network prune -f
		;;
	*)
		echo -e "#############################################"
		echo -e "######        \033[1;31mInvalid command:\033[0m         ######"
		echo -e "#############################################"
		echo  ""
		displayHelp
		exit 127;
		;;
esac

if [[ $proxyReverse == true ]]; then
	./proxy-reverse/red_proxy up
	# ./proxy-reverse/red_proxy default
fi


# Verificar si proxy-reverse/base.conf es igual a default.conf y eliminar el contenedor proxy-reverse si es así
if cmp -s "./proxy-reverse/base.conf" "./proxy-reverse/default.conf"; then
	echo "Eliminando el contenedor proxy-reverse."
	stoppingContainerProxyReverse
fi
