services:
  apis-app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MODE_CONTAINER: true
        NEXT_PUBLIC_API_BASE_PATH: /apisApp
        NEXT_PUBLIC_SWAGGER_URL: /api
        URL_EXTERNA_SIMULATOR: http://138.4.22.12/simulatorApp/
        URL_EXTERNA_SUBSCONTROLAPP: http://138.4.22.12/subsControlApp/
    image: ${IMAGE_APIS_APP_VERSION:-apis-app:v1}
    container_name: apis-app
    networks:
      - default
    # ports:
    #   - "3000:3000"
    #   - "3001:3001"
    environment:
      SERVER_PORT: 3001
      JWT_SECRET_KEY: ypb7SBzJ+3E6wXVy0dXQvAsyj7EYzFAhLBZ+CVmpdsCFK90OmwrU1VMykEl5hjHnKg/fjnjAsUCiQ+FMyYCkeg==
      ADMIN_EMAIL: admin@pass.es
      ADMIN_PASSWORD: admin1234
      DB_HOST: myql_apis-app
      DB_USER: root
      DB_PASSWORD: 12345678
      MONGODB_HOST: mongo-db-draco
      MONGODB_PORT: 27017
      MONGODB_NAME: sth_openiot
      REDIS_HOST: redis_apis-app
      REDIS_PORT: 6379
      LIMIT_API_KEY: 10
      TIME_LIMIT_API_KEY_M: 1
      MODE_CONTAINER: true
      NEXT_PUBLIC_MODE_CONTAINER: true

      # NEXT_PUBLIC_API_BASE_PATH: http://localhost:3000/apisApp
      API_BASE_URL : /apisApp
      NEXT_PUBLIC_API_BASE_PATH: /apisApp
      NEXT_PUBLIC_SWAGGER_URL: /api
    # volumes:
    #   - ./CityApiV3:/usr/src/app
    healthcheck:
      test: curl -k --fail -s http://apis-app:3001/ || exit 1
      interval: 5s
    depends_on:
      - mysql
      - redis


  mysql:
    # image: mysql:
    image: ${IMAGE_MYSQL_VERSION:-mysql:9.3.0}
    container_name: myql_apis-app
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: app_apis_database

  redis:
    # image: redis:latest
    image: ${IMAGE_REDIS_VERSION:-redis:8.0.2}
    networks:
      - default
    container_name: redis_apis-app
    ports:
      - "6379:6379"
    # volumes:
    #   - redis-data:/data


volumes:
  db-data:

networks:
  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24