services:
  mysql:
    image: mysql:latest
    container_name: app_apis_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: app_apis_database

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"