services:
  nginx-reverse:
    image: ${IMAGE_NGINX_REVERSE_VERSION:-nginx:1.28.0}
    container_name: nginx-reverse-container
    networks:
      - default
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/etc/nginx/html/index.html:ro
    healthcheck:
      test: curl -k --fail -s http://nginx-reverse-container:80/ || exit 1
      interval: 5s

networks:
  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24
