version: "3.8"

services:
  nginx-reverse:
    image: nginx-reverse 
    container_name: nginx-reverse-container
    networks:
      - default
    expose:
      - "80"
    ports:
      - "80:80"
      # - "8080:80"
    healthcheck:
      test: curl -k --fail -s http://nginx-reverse:80/ || exit 1
      interval: 5s

networks:
  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24