version: "3.8"
services:

  # Orion is the context broker
  nginx-reverse:
    image: nginx-reverse 
    container_name: nginx-reverse-container
    networks:
      - default
    expose:
      - 80
    ports:
      - 80:80



networks:
  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24