version: "3.8"

services:
  nginx-reverse:
    image: nginx-reverse 
    container_name: nginx-reverse-container
    networks:
      - my_custom_network
    expose:
      - "80"
    ports:
      - "80:80"

networks:
  my_custom_network:
    external:
      name: ${NET_NAME}