version: "3.8"

services:
  nginx-reverse:
    # image: nginx-reverse 
    image: nginx-reverse 
    container_name: nginx-reverse-container
    networks:
      # - proxy-reverse-net
      - default
    expose:
      - "80"
    ports:
      - "8080:80"

    healthcheck:
      test: curl -k --fail -s http://nginx-reverse:80/ || exit 1
      interval: 5s

networks:
  # proxy-reverse-net:
  #   external:
  #     name: ${NET_NAME}

  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24