services:
  minio:
    build: ./config_minio
    image: ${IMAGE_MINIO_CONFIGURED_VERSION:-minio_configured:v1}
    container_name: minio-bucket
    hostname: minioBucket
    networks:
      - default
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin123}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:-http://localhost:9001}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s

networks:
  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  minio-data:
