# weatherStation
### Activar la simulación
POST http://localhost:3030/weatherStation/toggle
Content-Type: application/json

{
  "state": true
}

### Desactivar la simulación
POST http://localhost:3030/weatherStation/toggle
Content-Type: application/json

{
  "state": false
}

