version: '3.1'
services:
  # https://localhost:9090/nifi/login


  draco:
    labels:
      org.fiware: 'draco'
    image: ging/fiware-draco:2.1.0
    container_name: draco
    environment:
      - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
    ports:
      - "9090:9090"
      - "5050:5050"
    # networks:
    #   - default
    # /opt/nifi/nifi-current
    # volumes:
    #   - draco-postgres-state:/opt
    healthcheck:
      test: curl -k --fail -s https://draco:9090/nifi/login || exit 1
      interval: 5s
  
  
  db-postgres-draco:
    labels:
      org.fiware: 'draco'
    image: postgres
    container_name: db-postgres-draco
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - "5432:5432"
    # networks:
    #   - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  # psql -h localhost -U postgres -p 5432 -d postgres

# volumes:
#   draco-postgres-state: 
#     labels:
#       org.fiware: 'state'

# networks:
#   default:
#     labels:
#       org.fiware: 'orion'
#     ipam:
#       config:
#         - subnet: 172.18.1.0/24