version: "3.8"
services:
  # https://localhost:9090/nifi/login
  draco:
    labels:
      org.fiware: 'draco'
    image: ging/fiware-draco:2.1.0
    container_name: draco
    environment:
      - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
    ports:
      - "9090:9090"
      - "5050:5050"
    healthcheck:
      test: curl -k --fail -s https://draco:9090/nifi/login || exit 1
      interval: 5s

  db-mysql-draco:
    labels:
      org.fiware: 'draco'
    image: mysql:5.7.22
    container_name: db-mysql-draco
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - "3306:3306"
    volumes:
    - mysql-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s

volumes:
  mysql-db:
    labels:
      org.fiware: 'draco'
