services:
  draco:
    labels:
      org.fiware: 'draco'
    # image: apache/nifi
    # image: apache/nifi:1.28.1
    # image: ging/fiware-draco:2.1.0
    # image: ging/fiware-draco:latest
    image: ${IMAGE_DRACO_VERSION:-apache/nifi:1.28.1}
    hostname: draco
    container_name: draco
    environment:
      - NIFI_WEB_HTTP_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
    networks:
      - default
    # ports:
    #   - "9090:9090"
    healthcheck:
      test: curl -k --fail -s http://draco:9090/nifi/login || exit 1
      interval: 5s
  
  draco-init:
    image: alpine:3.20
    depends_on:
      - draco
    volumes:
      - ./draco-ld-template:/draco-ld-template:ro
      - ./init-draco.sh:/init-draco.sh:ro
    # entrypoint: [ "sh", "-c", "apk add --no-cache curl jq && ls && /init-draco.sh" ]
    # entrypoint: [ "sh", "-c", "apk add --no-cache curl jq && /init-draco.sh && touch /tmp/draco-init.done && tail -f /dev/null" ]
    entrypoint: [ "sh", "-c", "apk add --no-cache curl jq && /init-draco.sh && touch /tmp/draco-init.done" ]
    environment:
      - NIFI_HOST=http://draco:9090
    networks:
      - default
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/draco-init.done"]
      interval: 2s
      retries: 10


  mongo-db-draco:
    labels:
        org.fiware: 'draco'
    # image: mongo:${MONGO_DB_VERSION}
    # image: mongo:4.4
    image: ${IMAGE_MONGO_DB_VERSION:-mongo:4.4}
    container_name: mongo-db-draco
    restart: always
    ports:
      - "27017:27017"
    networks:
      - default
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1    
      interval: 5s


  # mongo-express-draco:
  #   # image: mongo-express
  #   image: ${IMAGE_MONGO_EXPRESS_VERSION:-mongo-express:1.0.2}
  #   container_name: mongo-express-draco
  #   restart: always
  #   environment:
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=pass123
  #     - ME_CONFIG_MONGODB_SERVER=mongo-db-draco
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_URL=mongodb://@mongo-db-draco:27017/
  #   depends_on:
  #     - mongo-db-draco


networks:
  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24