version: '3.8'

services:
  draco:
    labels:
      org.fiware: 'draco'
    image: apache/nifi
    hostname: draco
    container_name: draco
    expose:
      - "9090"
    environment:
      - NIFI_WEB_HTTP_PORT=9090
      # - SINGLE_USER_CREDENTIALS_USERNAME=admin
      # - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
    networks:
      - default
    ports:
      - "9090:9090"
      - "5050:5050"
    healthcheck:
      test: curl -k --fail -s http://draco:9090/nifi/login || exit 1
      interval: 5s


  mongo-db-draco:
    labels:
        org.fiware: 'draco'
    image: mongo:${MONGO_DB_VERSION}
    container_name: mongo-db-draco
    restart: always
    ports:
      - "27017:27017"
    networks:
      - default
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1    
      interval: 5s

networks:

  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24