version: '3.8'

services:
  draco:
    labels:
      org.fiware: 'draco'
    # image: apache/nifi
    image: apache/nifi:1.28.1
    # image: ging/fiware-draco:2.1.0
    # image: ging/fiware-draco:latest
    hostname: draco
    container_name: draco
    environment:
      - NIFI_WEB_HTTP_PORT=9090
      # - NIFI_WEB_HTTP_PORT=9090
      # - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
      # - NIFI_WEB_PROXY_HOST=draco
    networks:
      - default
    # expose:
    #   - "9090"
    ports:
      - "9090:9090"
    #   - "5050:5050"
    healthcheck:
      test: curl -k --fail -s http://draco:9090/nifi/login || exit 1
      # test: curl -k --fail -s https://localhost:9090/nifi/#/login || exit 1
      # test: curl -k --fail -s https://127.0.0.1:9090/nifi/login || exit 1
      # test: curl -k --fail -s https://draco:9090/nifi/#/login || exit 1
      # test: curl -k --fail -s http://draco:9090/nifi/login || exit 1
      interval: 5s

  mongo-db-draco:
    labels:
        org.fiware: 'draco'
    # image: mongo:${MONGO_DB_VERSION}
    image: mongo:4.4
    container_name: mongo-db-draco
    restart: always
    # ports:
    #   - "27017:27017"
    networks:
      - default
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1    
      interval: 5s


  mongo-express-draco:
    image: mongo-express
    container_name: mongo-express-draco
    restart: always
    # ports:
    #   - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo-db-draco
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://@mongo-db-draco:27017/
    depends_on:
      - mongo-db-draco



networks:

  default:
    labels:
      org.fiware: 'orion'
    ipam:
      config:
        - subnet: 172.18.1.0/24